pub static PALWORLD_TYPE_HINTS: &[(&str, &str)] = &[
    (
        ".worldSaveData.CharacterContainerSaveData.Key",
        "StructProperty",
    ),
    (
        ".worldSaveData.CharacterSaveParameterMap.Key",
        "StructProperty",
    ),
    (
        ".worldSaveData.CharacterSaveParameterMap.Value",
        "StructProperty",
    ),
    (
        ".worldSaveData.FoliageGridSaveDataMap.Key",
        "StructProperty",
    ),
    (
        ".worldSaveData.FoliageGridSaveDataMap.Value.ModelMap.Value",
        "StructProperty",
    ),
    (
        ".worldSaveData.FoliageGridSaveDataMap.Value.ModelMap.Value.InstanceDataMap.Key",
        "StructProperty",
    ),
    (
        ".worldSaveData.FoliageGridSaveDataMap.Value.ModelMap.Value.InstanceDataMap.Value",
        "StructProperty",
    ),
    (
        ".worldSaveData.FoliageGridSaveDataMap.Value",
        "StructProperty",
    ),
    (".worldSaveData.ItemContainerSaveData.Key", "StructProperty"),
    (
        ".worldSaveData.MapObjectSaveData.MapObjectSaveData.ConcreteModel.ModuleMap.Value",
        "StructProperty",
    ),
    (
        ".worldSaveData.MapObjectSaveData.ConcreteModel.ModuleMap.Value",
        "StructProperty",
    ),
    (
        ".worldSaveData.MapObjectSaveData.MapObjectSaveData.Model.EffectMap.Value",
        "StructProperty",
    ),
    (
        ".worldSaveData.MapObjectSaveData.Model.EffectMap.Value",
        "StructProperty",
    ),
    (
        ".worldSaveData.MapObjectSpawnerInStageSaveData.Key",
        "StructProperty",
    ),
    (
        ".worldSaveData.MapObjectSpawnerInStageSaveData.Value",
        "StructProperty",
    ),
    (
        ".worldSaveData.MapObjectSpawnerInStageSaveData.Value.SpawnerDataMapByLevelObjectInstanceId.Key",
        "Guid",
    ),
    (
        ".worldSaveData.MapObjectSpawnerInStageSaveData.Value.SpawnerDataMapByLevelObjectInstanceId.Value",
        "StructProperty",
    ),
    (
        ".worldSaveData.MapObjectSpawnerInStageSaveData.Value.SpawnerDataMapByLevelObjectInstanceId.Value.ItemMap.Value",
        "StructProperty",
    ),
    (
        ".worldSaveData.WorkSaveData.WorkSaveData.WorkAssignMap.Value",
        "StructProperty",
    ),
    (".worldSaveData.BaseCampSaveData.Key", "Guid"),
    (".worldSaveData.BaseCampSaveData.Value", "StructProperty"),
    (
        ".worldSaveData.BaseCampSaveData.Value.ModuleMap.Value",
        "StructProperty",
    ),
    (
        ".worldSaveData.ItemContainerSaveData.Value",
        "StructProperty",
    ),
    (
        ".worldSaveData.CharacterContainerSaveData.Value",
        "StructProperty",
    ),
    (".worldSaveData.GroupSaveDataMap.Key", "Guid"),
    (".worldSaveData.GroupSaveDataMap.Value", "StructProperty"),
    (
        ".worldSaveData.EnemyCampSaveData.EnemyCampStatusMap.Value",
        "StructProperty",
    ),
    (
        ".worldSaveData.DungeonSaveData.DungeonSaveData.MapObjectSaveData.MapObjectSaveData.Model.EffectMap.Value",
        "StructProperty",
    ),
    (
        ".worldSaveData.DungeonSaveData.DungeonSaveData.MapObjectSaveData.Model.EffectMap.Value",
        "StructProperty",
    ),
    (
        ".worldSaveData.DungeonSaveData.DungeonSaveData.MapObjectSaveData.MapObjectSaveData.ConcreteModel.ModuleMap.Value",
        "StructProperty",
    ),
    (
        ".worldSaveData.DungeonSaveData.DungeonSaveData.MapObjectSaveData.ConcreteModel.ModuleMap.Value",
        "StructProperty",
    ),
    (".worldSaveData.InvaderSaveData.Key", "Guid"),
    (".worldSaveData.InvaderSaveData.Value", "StructProperty"),
    (
        ".worldSaveData.OilrigSaveData.OilrigMap.Value",
        "StructProperty",
    ),
    (".worldSaveData.SupplySaveData.SupplyInfos.Key", "Guid"),
    (
        ".worldSaveData.SupplySaveData.SupplyInfos.Value",
        "StructProperty",
    ),
    (".worldSaveData.GuildExtraSaveDataMap.Key", "Guid"),
    (
        ".worldSaveData.GuildExtraSaveDataMap.Value",
        "StructProperty",
    ),
    (
        ".worldSaveData.EnemyCampSaveData.EnemyCampStatusMap.Value.TreasureBoxInfoMapBySpawnerName.Value",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.CharacterSaveParameterMap.MapProperty.Key.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.CharacterSaveParameterMap.MapProperty.Value.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.MapObjectSaveData.ArrayProperty.ConcreteModel.StructProperty.ModuleMap.MapProperty.Value.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.MapObjectSaveData.ArrayProperty.Model.StructProperty.EffectMap.MapProperty.Value.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.FoliageGridSaveDataMap.MapProperty.Key.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.FoliageGridSaveDataMap.MapProperty.Value.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.FoliageGridSaveDataMap.MapProperty.Value.StructProperty.ModelMap.MapProperty.Value.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.FoliageGridSaveDataMap.MapProperty.Value.StructProperty.ModelMap.MapProperty.Value.StructProperty.InstanceDataMap.MapProperty.Key.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.FoliageGridSaveDataMap.MapProperty.Value.StructProperty.ModelMap.MapProperty.Value.StructProperty.InstanceDataMap.MapProperty.Value.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.MapObjectSpawnerInStageSaveData.MapProperty.Key.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.MapObjectSpawnerInStageSaveData.MapProperty.Value.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.MapObjectSpawnerInStageSaveData.MapProperty.Value.StructProperty.SpawnerDataMapByLevelObjectInstanceId.MapProperty.Key.StructProperty",
        "Guid",
    ),
    (
        ".worldSaveData.StructProperty.MapObjectSpawnerInStageSaveData.MapProperty.Value.StructProperty.SpawnerDataMapByLevelObjectInstanceId.MapProperty.Value.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.MapObjectSpawnerInStageSaveData.MapProperty.Value.StructProperty.SpawnerDataMapByLevelObjectInstanceId.MapProperty.Value.StructProperty.ItemMap.MapProperty.Value.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.WorkSaveData.ArrayProperty.WorkAssignMap.MapProperty.Value.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.BaseCampSaveData.MapProperty.Key.StructProperty",
        "Guid",
    ),
    (
        ".worldSaveData.StructProperty.BaseCampSaveData.MapProperty.Value.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.BaseCampSaveData.MapProperty.Value.StructProperty.ModuleMap.MapProperty.Value.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.ItemContainerSaveData.MapProperty.Key.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.ItemContainerSaveData.MapProperty.Value.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.CharacterContainerSaveData.MapProperty.Key.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.CharacterContainerSaveData.MapProperty.Value.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.GroupSaveDataMap.MapProperty.Key.StructProperty",
        "Guid",
    ),
    (
        ".worldSaveData.StructProperty.GroupSaveDataMap.MapProperty.Value.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.GuildExtraSaveDataMap.MapProperty.Key.StructProperty",
        "Guid",
    ),
    (
        ".worldSaveData.StructProperty.GuildExtraSaveDataMap.MapProperty.Value.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.EnemyCampSaveData.StructProperty.EnemyCampStatusMap.MapProperty.Value.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.EnemyCampSaveData.StructProperty.EnemyCampStatusMap.MapProperty.Value.StructProperty.TreasureBoxInfoMapBySpawnerName.MapProperty.Value.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.DungeonSaveData.ArrayProperty.MapObjectSaveData.ArrayProperty.ConcreteModel.StructProperty.ModuleMap.MapProperty.Value.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.InvaderSaveData.MapProperty.Key.StructProperty",
        "Guid",
    ),
    (
        ".worldSaveData.StructProperty.InvaderSaveData.MapProperty.Value.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.OilrigSaveData.StructProperty.OilrigMap.MapProperty.Value.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.SupplySaveData.StructProperty.SupplyInfos.MapProperty.Key.StructProperty",
        "Guid",
    ),
    (
        ".worldSaveData.StructProperty.SupplySaveData.StructProperty.SupplyInfos.MapProperty.Value.StructProperty",
        "StructProperty",
    ),
    (
        ".worldSaveData.StructProperty.InLockerCharacterInstanceIDArray.SetProperty.StructProperty",
        "StructProperty",
    ),
];

pub static DISABLED_PROPERTIES: &[&str] = &[".worldSaveData.BaseCampSaveData.Value.ModuleMap"];
